"""empty message

Revision ID: e6a863d2c560
Revises: 20bb46e721a9
Create Date: 2017-08-16 13:43:54.779060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a863d2c560'
down_revision = '20bb46e721a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
